POST  http://localhost:8000/api/v1/products
Content-Type: application/json

[
  "62b057191d3c44dc152ab25a",
  "62b0571f1d3c44dc152ab25d",
  "62b057251d3c44dc152ab260",
  "62b057941d3c44dc152ab26c"
]


### get categories by parentcatId
GET http://localhost:8000/api/v1/categories/62b056fd1d3c44dc152ab251


### get customer
GET http://localhost:8000/api/v1/customer

### post customer
POST http://localhost:8000/api/v1/customer
Content-Type: application/json

{
  "fName":"Dipak",
  "lName":"Paudel",
  "email":"paudelsantosh509@gmail.com",
  "password":"asdfawewef",
  "address":"3/25 cecil street",
  "phone":"0452450087",
  "dob":"01/08/1999"
}


### update customer
PUT http://localhost:8000/api/v1/customer



