POST  http://localhost:8000/api/v1/products
Content-Type: application/json

[
  "62b057191d3c44dc152ab25a",
  "62b0571f1d3c44dc152ab25d",
  "62b057251d3c44dc152ab260",
  "62b057941d3c44dc152ab26c"
]

###get all products
GET  http://localhost:8000/api/v1/products




### get categories by parentcatId
GET http://localhost:8000/api/v1/categories/62b056fd1d3c44dc152ab251


### get customer
GET http://localhost:8000/api/v1/customer

### post customer
PUT  http://localhost:8000/api/v1/customer
Content-Type: application/json

{
  "fName":"Diplak",
  "lName":"paudel",
  "email":"paudelsan@gmail.com",
  "password":"dipak1234",
  "address":"3/25 cecil street,Ashfield,NSW 2131",
  "phone":"0452450089",
  "dob":"02/08/1999"
}


### update customer
PUT http://localhost:8000/api/v1/customer

### login customer
POST http://localhost:8000/api/v1/customer/login
Content-Type: application/json

{
  "email":"paudelsantosh507gmail.com",
  "password":"asdfawewef"
}




### stripe
POST  http://localhost:8000/api/v1/stripe
Content-Type: application/json

{"items":[{"_id":"62c3ae7ed51c361f2b2ea95b", "quantity":2},{"_id":"63058ebe8b9b0fedf91749a4", "quantity":2}]}
